name: Auto Format Python Code

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatters (isort, black)
        run: |
          python -m pip install --upgrade pip
          pip install isort black

      - name: Run isort
        run: isort .

      - name: Run black
        run: black .

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "style: auto-format with isort and black"
          git push
